worker_processes auto;
events { worker_connections 1024; }
http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    tcp_nopush    on;
    tcp_nodelay   on;
    keepalive_timeout 65;
    client_max_body_size 0;

    map $request_method $ts_method {
        default $request_method;
        HEAD    GET;
    }

    server {
        listen 80;
        server_name _;

        location ~ ^/(boot|smile_reactions)\.js$ {
            proxy_pass http://lampa:80;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_hide_header ETag;
            proxy_hide_header Last-Modified;
            add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0" always;
            add_header Pragma "no-cache" always;
            add_header Expires "0" always;
        }

        location / {
            proxy_pass http://lampa:80;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
